### ISSUE TITLE
[Feature-Request] Add/remove pump schedules via mqtt

### ISSUE THREAD

**Issue by NemoN** [LordMike/MBW.BlueRiiot2MQTT#17]
would be a nice feature to add/remove pump schedules from mqtt because my pump is triggered from home automation system.

![Screenshot_20200715-142138_Blueriiot](https://user-images.githubusercontent.com/2212175/87544731-40f72c00-c6a7-11ea-9886-55b415a72af0.jpg)

**Comment by LordMike** [comment]
So how would this work?

You want to change the schedule on BR, when your pump starts, to "now .. +4 hours", and then when the pump stops, change it to "manual" ?

**Comment by NemoN** [comment]
Good question. I hadn't really thought about the details yet.
Are measurements taken when the pump is set to "manual" but "activated"?
Then it would be enough to activate and deactivate the pump (in BR) via MQTT. (And to leave it on mode manual)

**Comment by ggggh** [comment]
I'm confused too :)  This project only captures measurements, it doesn´t manage pumps or know about them.  I, like you, have integrated it with my pump, but that is external to this project.

**Comment by LordMike** [comment]
I'll gladly consider writing back to BlueRiiot.. but in general I'd prefer if settings and configuration were done in the app, as it is after all designed for just that. 

I don't think the pump settings affect the measurements in any way.. then again, I haven't looked that much into it. I would *think* that the details would be used to discard measurements taking during the pump's operation so that any outliers in those periods can be ignored.

**Comment by ggggh** [comment]
Ah, starting to understand this maybe...  Is this for the case where the blueriiot is integrated within your pump tubing, rather than floating on the pool, so we should only consider values when there is actually water flowing in the tubing?

**Comment by NemoN** [comment]
Sorry i missed this important point. Yes the blueriiot is integrated into the tubing (using the BlueFit 50).
I have only valid measurements if the pump is running. This i why we can enter the pump schedule into the App (then the App is only showing measurements within the timerange). Now i want to trigger the pump from ioBroker (HA). I this case it could be that the pump is running, but blueriiot thinks it is not (because the static schedule not match).

**Comment by ggggh** [comment]
Right...I understand it now!  So you would like either the schedule to be returned within the messages (maybe a topic stating if pump running or not, so you can then decide to ignore the rest of the values), or even no messages sent at all while pump is not running

**Comment by LordMike** [comment]
But wouldn't BR then only show you the current readings... for all time.. 

What I mean is .. If you set it to 02:00 to 05:00, can you see *yesterdays* 07:00 reading?.. 

Or will it _discard_ any readings _right now_ ... f.ex. if you set it to 02:00 to 05:00, will a reading at 03:00 be stored, while 01:00 will be ignored ? ...

**Comment by NemoN** [comment]
> But wouldn't BR then only show you the current readings... for all time..
> 
> What I mean is .. If you set it to 02:00 to 05:00, can you see _yesterdays_ 07:00 reading?..
> 
> Or will it _discard_ any readings _right now_ ... f.ex. if you set it to 02:00 to 05:00, will a reading at 03:00 be stored, while 01:00 will be ignored ? ...

If i enable the scheduled pump running times in BR i see only readings within the configured time-range. all other readings (if any?) are ignored or not shown to me in the frontend.

**Comment by NemoN** [comment]
Looks like with dynamic pump runtimes I have to set the value at BR to **manual** and then ignore all values where the pump is off.

**Comment by LordMike** [comment]
@NemoN did you find out if changing pump schedules was necessary?

... also.. should this app make any effort to not track values, outside of pump schedules? ... I didn't catch if BR stops measuring whenever pumps are off. If they still make measurements (but just don't show them) ... I'd have to do something to handle that.. :P

**Comment by LordMike** [comment]
At least from the above,

> If i enable the scheduled pump running times in BR i see only readings within the configured time-range. all other readings (if any?) are ignored or not shown to me in the frontend.

I can conclude that setting the pump schedule to "now and 4 hours" whenever you turn on the pump, does not make sense. Also, setting the schedule to have BR stop reporting static/unchanging values from a Fit-50 mount, doesn't make sense.

Did you @NemoN decide if you wanted this app to do something? .. I don't think we can get HASS to ignore values if some other condition is met.. ... Maybe I should have a "disable updates" topic that you can send "yes" and "no" to, which temporarily stops fetching values ?

**Comment by ggggh** [comment]
I'd agree - I think the master for the pump schedule is not blueriiot, so we shouldn't treat it as such.  Whatever is mastering your pump automation via a schedule should handle ignoring the readings from blueriiot when the pump is off - either by sending an mqtt to disable readings for that period, or just ignoring them when they come back in during that timeframe.

**Comment by LordMike** [comment]
... and the ignoring of messages on HASS... is that possible?

Else the only option we have is my app _not sending any_.

... [it's not possible](https://github.com/home-assistant/core/blob/d7d7ee6524114ef132b8c996974825d13abb3f7c/homeassistant/components/mqtt/sensor.py#L147-L173).

**Comment by ggggh** [comment]
Ah, ok - I don't know HASS, but I'm assuming maybe not ignoring the message itself, but ignoring or disabling actions/alarms/triggers on it should be do-able.

**Comment by NemoN** [comment]
@LordMike Sorry I'm late, I'm on vacation. For me it would be enough if I could switch the pump mode on/off via MQTT. 
Not the real pump. I mean the pump setting in the BR app (see first screenshot - the first setting)
Would that be possible?

**Comment by LordMike** [comment]
I'll look into it.

**Comment by gllmlbrt** [comment]
Hi there,
I have the same setup as @NemoN and I was frankly wondering about the exact same things. Essentially the issue is getting readings while the pump is off, meaning that the BR tells you the water quality of the water stagnating in the pipe which is not a real useful/valid information.
Now based on the discussion I realize that the app may deal with that already with pump schedule, and then in Hass we have to find out what is the difference between a reading received over mqtt within the pump-on schedule and pump-off time.

Just thinking and writing here:
Now what would be REALLY neat would be that, the pump schedule defined in the app is transmitted over MQTT, 

-then read by Hass and the pump is then activated for that schedule via on-off switching method in place in hass (for me it is a Sonoff PowR2 tasmotized over mqtt

-or directly over mqtt.
It could just be a publication of cmnd/Power on or off from the BlueRiiot2MQTT docker app, based on the BR app schedule, bypassing entirely hass ?
That would effectively make the BR app the scheduling method for the pump, instead of the multiple automations/scripts needed in hass... and ensure full consistency between what is in BR app and the real pump schedule.

**Comment by LordMike** [comment]
My thinking is that the only way to make this good, is to not send data to HASS that HASS doesn't need. So it has to stop at this app. This is in order to fix multiple things, such as the Recorder not logging invalid data, automations not having to account for on/off etc.. everything is just easier when the data you receive is valid.

So how to block it in this app. 

I'm fond of the idea of letting my app read the pump timings from BR, as I've always wanted you guys to use the BR app for everything BR.. So if I did that, I could parse it and do the (hopefully) same logic as BR, and not submit readings that are outside the pump schedules.

Does this require being able to push pump schedules via MQTT?

**Comment by gllmlbrt** [comment]
> I'm fond of the idea of letting my app read the pump timings from BR, as I've always wanted you guys to use the BR app for everything BR.. So if I did that, I could parse it and do the (hopefully) same logic as BR, and not submit readings that are outside the pump schedules.

Yes that would be the original idea, for those with the FIT50 mounted on the piping.

> Does this require being able to push pump schedules via MQTT?

That would be only useful for my secondary idea which is that once the schedule is sent over mqtt, we can do what we want with it, including mastering the actual pump switch...

Ideally, and simplistically it would be only a publication of "on" or "off" from your app in line with the BR app schedule, then we can use that to convert into whatever mqtt command to our pump or anything else.

**Comment by ggggh** [comment]
I'd only like to suggest I personally wouldn't want to master the pump schedule from the BR app itself.  
The reason is that for a full automation I make the pump schedule dependent on ORP and pH values.   
I have my pump run based on a minimum number of hours of filtration a day, but especially have it come on ad-hoc when it needs to dose some acid or activate the chlorinator.   If you've got your BR set up with the BlueFit..it gets more complicated.  You need the pump to come on before you take a reading and then decide whether it needs to stay on or not.  With the new predicted reading times you may be able to schedule the pump to come on shortly before the next reading happens - but it is a bit sketchy as not always totally predictable.  If we could trigger a reading, would be much easier.

**Comment by gllmlbrt** [comment]
> I'd only like to suggest I personally wouldn't want to master the pump schedule from the BR app itself.

Noted, and if the only thing the @LordMike app does is publish and on/off message based on BR app schedule, we are all free to ignore it.

> The reason is that for a full automation I make the pump schedule dependent on ORP and pH values.

Do you mind sharing your config automation, I am curious and I looked for inspiration as well ?

**Comment by LordMike** [comment]
So, I'll try to make:

* A Sensor that reports the pump schedule(s), probably one sensor per Blue device, or per Pool
* A command that can set the pump schedule

I'm not sure about this part, 

> Ideally, and simplistically it would be only a publication of "on" or "off" from your app in line with the BR app schedule, then we can use that to convert into whatever mqtt command to our pump or anything else.

Do you want, in addition to a sensor describing the schedule, another (binary) sensor that is "BR pump schedule says it's active"? ... a sensor that in reality has nothing to do with BR, but is merely to help with other things so they don't have to parse time ranges?

**Comment by LordMike** [comment]
Oh god.. the pump schedules in the API.. they hurt my brain...

![image](https://user-images.githubusercontent.com/1027111/90684495-96a39300-e268-11ea-9d38-5fbf77b635b3.png)

I've set three schedules:

* `00:00` -> `04:00` (first 4 hours)
* `00:00` -> `00:00` (full day)
* `20:00` -> `00:00` (last 4 hours)

So not only do BR store this as _timestamps_... they've messed completely with the dates. Notice the last one, which starts on the 19th and ends on the 18th..

Oh well..

**Comment by LordMike** [comment]
I have working code for fetching and setting of the pump schedules.

![image](https://user-images.githubusercontent.com/1027111/90698803-f65a6800-e281-11ea-93b0-58fec6f72ae0.png)

**Comment by LordMike** [comment]
A docker image should be building. Give `dev` a whirl and see what happens.

Notes:

* Currently, times shown are UTC. ... should I convert to some timezone? .. which?..
* Times provided to BR2MQTT must also be UTC
* I need to know if the attributes make sense, and what others might be used in addition / instead of those I've picked
* There is a _risk_ that I'll destroy / alter the pool you have configured. The API requires that I send back _all_ of the pool settings (name, type, volume, ..) to set the schedule.. I've taken special care to get and send back all data, both known and unknown... but accidents can happen.. Let me know if a setting disappears when you set a schedule.

**Comment by LordMike** [comment]
No comments - @NemoN @ggggh @Nordicfastware  ? :)

**Comment by NemoN** [comment]
@LordMike just back from vacation, will test it asap.

**Comment by NemoN** [comment]
@LordMike works perfect for me!

MQTT pub:
```
# mosquitto_pub -h localhost -t blueriiot/commands/pool/1234-xxx/set_pump_schedule -m manual
# mosquitto_pub -h localhost -t blueriiot/commands/pool/1234-xxx/set_pump_schedule -m none
# mosquitto_pub -h localhost -t blueriiot/commands/pool/1234-xxx/set_pump_schedule -m '[["07:00", "10:00"],["16:00", "17:00"]]'
```
MQTT sub:
```
blueriiot/commands/pool/1234-xxx/set_pump_schedule manual
blueriiot/pool_1234-xxx/pump_schedule/state Manual
blueriiot/pool_1234-xxx/pump_schedule/attributes {"pool_id":"1234-xxx"}
blueriiot/commands/pool/1234-xxx/set_pump_schedule none
blueriiot/pool_1234-xxx/pump_schedule/state None
blueriiot/pool_1234-xxx/pump_schedule/attributes {"pool_id":"1234-xxx"}
blueriiot/commands/pool/1234-xxx/set_pump_schedule [["07:00", "10:00"],["16:00", "17:00"]]
blueriiot/pool_1234-xxx/pump_schedule/state Scheduled
blueriiot/pool_1234-xxx/pump_schedule/attributes {"pool_id":"1234-xxx","schedule":"07:00-10:00, 16:00-17:00","schedules":2,"schedule_0":"07:00-10:00","schedule_0_start":"07:00","schedule_0_end":"10:00","schedule_1":"16:00-17:00","schedule_1_start":"16:00","schedule_1_end":"17:00"}
```
All other pool settings in the app seems to be ok.

**Comment by LordMike** [comment]
Due to other issues, the feature is also in `v0.8`

**Comment by LordMike** [comment]
Cool. If you have any comments on the format of arguments etc, place them here - I'll take a look when I have time. 

I don't know how to use this in any automations, so if it's easier f.ex. to have a series of numbers, like `7,10,16,17` ... then I could do that.. Can also do multiple formats.

Same goes for the output, the HASS sensor. I don't know if the format I've chosen is easy to use in automations - but give it a whirl :)
